# Auto-generated by scripts/calibrate.py — do not edit by hand.
# Source: Cinderhaven Postgres percentile distributions (2023-2026 window).
# Re-run calibrate.py against updated data before changing thresholds.

# Scoring direction: 5 = best, 1 = worst.
# For "lower is better" dimensions (shelf_space_cost, production_complexity,
# cannibalization_risk), score 5 is assigned at LOW raw values.

# --- Velocity (units/store/week) ---
# Score 5: >= p75, Score 4: p50–p75, Score 3: p25–p50,
# Score 2: p10–p25, Score 1: < p10
VELOCITY_P10 = 2.0201
VELOCITY_P25 = 4.3606
VELOCITY_P50 = 8.3338
VELOCITY_P75 = 13.5066
VELOCITY_P90 = 18.2600

# --- Contribution margin (loaded_margin_pct, 0.0–1.0) ---
# Set 2026-09-28 from production after the platform case-pack COGS fix
# (4e9f37a); the other dimensions are still the 2026-06-28 calibration, so
# the next calibrate.py run will also move them.
MARGIN_P10 = 0.4352
MARGIN_P25 = 0.4843
MARGIN_P50 = 0.5199
MARGIN_P75 = 0.5564
MARGIN_P90 = 0.6066

# --- Shelf-space cost (annual USD) — lower is better ---
# Score 5: ≤ p25, Score 4: p25–p50, Score 3: p50–p75,
# Score 2: p75–p90, Score 1: > p90
SHELF_P10 = 24128.67
SHELF_P25 = 40136.32
SHELF_P50 = 74765.20
SHELF_P75 = 119627.83
SHELF_P90 = 137925.29

# --- Production complexity proxy (landed_cost/msrp ratio) — lower is better ---
COMPLEX_P10 = 0.2284
COMPLEX_P25 = 0.2475
COMPLEX_P50 = 0.2701
COMPLEX_P75 = 0.3012
COMPLEX_P90 = 0.3167

# --- Cannibalization risk (inverted velocity delta) — lower is better ---
# 0.0 = no signal, positive = velocity drops in shared stores.
#
# HIGH / VERY_HIGH are fixed cutoffs, NOT percentiles of the shipped per-SKU
# values. 36 of 50 SKUs are zeroed by the <3-solo-stores rule, so per-SKU
# percentiles measure the zero mass, not cannibalization intensity (the shipped
# p75 is 0.0191 — barely nonzero). These cutoffs are calibrated on the pre-zeroing
# PAIRS distribution (int_cannibalization_pairs), where the metric is actually
# defined — the 75th/90th percentiles among SKUs whose cannibalization is
# measurable. See docs/scoring_methodology.md. (P10/P25/P50 are 0.0 either way.)
CANNIBAL_P10 = 0.0000
CANNIBAL_P25 = 0.0000
CANNIBAL_P50 = 0.0000
CANNIBAL_HIGH = 0.0745       # pairs-distribution p75 (measurable-SKU high threshold)
CANNIBAL_VERY_HIGH = 0.2054  # pairs-distribution p90 (measurable-SKU very-high threshold)
